from tkinter import *
def sel():
   selection = "You selected the option " + str(var.get())
   if(selection=="You selected the option 1"):    
       l=Label(root,text='Wrong answer!Better luck next time')
       l.config(bg="RED",fg="WHITE")
       l.pack()
   elif(selection=="You selected the option 2"):
       l=Label(root,text='Right answer....... Congrats you won 30000 rs')
       l.config(bg="GREEN",fg="WHITE")
       l.pack()
   elif(selection=="You selected the option 3"):
       l=Label(root,text='Wrong answer!Better luck next time ')
       l.config(bg="RED",fg="WHITE")
       l.pack()
   elif(selection=="You selected the option 4"):
       l=Label(root,text='Wrong answer!Better luck next time')
       l.config(bg="RED",fg="WHITE")
       l.pack()          
   label.config(text = selection)
def mel():
   selection = "You selected the option " + str(var.get())
   if(selection=="You selected the option 1"):    
       l=Label(root,text='Right answer.......Congrats you won 3000000 rs')
       l.config(bg="GREEN",fg="WHITE")
       l.pack()
   elif(selection=="You selected the option 2"):
       l=Label(root,text='Wrong answer! Your winning amount is 300000 rs')
       l.config(bg="RED",fg="WHITE")
       l.pack()
   elif(selection=="You selected the option 3"):
       l=Label(root,text='Wrong answer! Your winning amount is 300000 rs')
       l.config(bg="RED",fg="WHITE")
       l.pack()
   elif(selection=="You selected the option 4"):
       l=Label(root,text='Wrong answer! Your winning amount is 300000 rs')
       l.config(bg="RED",fg="WHITE")
       l.pack()          
   label.config(text = selection)
def tel():
   selection = "You selected the option " + str(var.get())
   if(selection=="You selected the option 1"):    
       l=Label(root,text='Wrong answer! Your winning amount is 3000000 rs')
       l.config(bg="RED",fg="WHITE")
       l.pack()
   elif(selection=="You selected the option 2"):
       l=Label(root,text='Wrong answer! Your winning amount is 3000000 rs')
       l.config(bg="RED",fg="WHITE")
       l.pack()
   elif(selection=="You selected the option 3"):
       l=Label(root,text='Wrong answer! Your winning amount is 3000000 rs')
       l.config(bg="RED",fg="WHITE")
       l.pack()
   elif(selection=="You selected the option 4"):
       l=Label(root,text='Right answer..........Congrats you won 30000000 rs')
       l.config(bg="GREEN",fg="WHITE")
       l.pack()          
def Rel():
   selection = "You selected the option " + str(var.get())
   if(selection=="You selected the option 1"):    
       l=Label(root,text='Wrong answer! Your winning amount is 30000000 rs')
       l.config(bg="RED",fg="WHITE")
       l.pack()
   elif(selection=="You selected the option 2"):
       l=Label(root,text='Wrong answer! Your winning amount is 30000000 rs')
       l.config(bg="RED",fg="WHITE")
       l.pack()
   elif(selection=="You selected the option 3"):
       l=Label(root,text='Right answer..........Congrats you won 300000000 rs')
       l.config(bg="GREEN",fg="WHITE")
       l.pack()
   elif(selection=="You selected the option 4"):
       l=Label(root,text='Wrong answer!Your winning amount is 30000000 rs')
       l.config(bg="RED",fg="WHITE")
       l.pack()
                 
   label.config(text = selection)
root = Tk()
var = IntVar()
root.config(bg="PURPLE")
root.title("KBC quiz Interface")

l1=Label(root,text='***********************WELCOME TO kAUN BANEGA CROREPATI**************************')
l1.config(bg="ORANGE")
l1.pack()

l1=Label(root,text='*********************************IF YOU FAIL, THEN FINAL QUESTION AMOUNT WILL BE REWARDED TO YOU*****************************')
l1.config(bg="ORANGE")
l1.pack()
l1=Label(root,text="")
l1.pack()
l1=Label(root,text='Question 1:- The internationl literacy day is observed on?')
l1.config(bg="GOLD")
l1.pack()
R1 = Radiobutton(root, text="Option 1 = Nov 28", variable=var, 				value=1, command=sel)
R1.config(bg="CYAN")
R1.pack( anchor = W )
R2 = Radiobutton(root, text="Option 2 = Sep 8", variable=var, 				value=2,command=sel)
R2.config(bg="CYAN")
R2.pack( anchor = W )
R3 = Radiobutton(root, text="Option 3 = May 2", variable=var, 				value=3,command=sel)
R3.config(bg="CYAN")
R3.pack( anchor = W)
R4 = Radiobutton(root, text="Option 4 = Sep 22", variable=var, 				value=4,command=sel)
R4.config(bg="CYAN")
R4.pack( anchor = W)
l1=Label(root,text='Question 2:- The language of lakshadeep. a Union Territory of India, is')
l1.config(bg="GOLD")
l1.pack()
R1 = Radiobutton(root, text="Option 1 = Malayalam", variable=var, 				value=1, command=mel)
R1.config(bg="CYAN")
R1.pack( anchor = W )
R2 = Radiobutton(root, text="Option 2 = Tamil", variable=var, 				value=2,command=mel)
R2.config(bg="CYAN")
R2.pack( anchor = W )
R3 = Radiobutton(root, text="Option 3 = Hindi", variable=var, 				value=3,command=mel)
R3.config(bg="CYAN")
R3.pack( anchor = W)
R4 = Radiobutton(root, text="Option 4 = Telugu", variable=var, 				value=4,command=mel)
R4.config(bg="CYAN")
R4.pack( anchor = W)
l1=Label(root,text='Question 3:- Scientific name of lotus is?')
l1.config(bg="GOLD")
l1.pack()
R1 = Radiobutton(root, text="Option 1 = Jasmium sambac", variable=var, 				value=1, command=tel)
R1.config(bg="CYAN")
R1.pack( anchor = W )
R2 = Radiobutton(root, text="Option 2 = Lillium", variable=var, 				value=2,command=tel)
R2.config(bg="CYAN")
R2.pack( anchor = W )
R3 = Radiobutton(root, text="Option 3 = Paeonia", variable=var, 				value=3,command=tel)
R3.config(bg="CYAN")
R3.pack( anchor = W)
R4 = Radiobutton(root, text="Option 4 = Nelumbo nucifera", variable=var, 				value=4,command=tel)
R4.config(bg="CYAN")
R4.pack( anchor = W)
l1=Label(root,text='Question 4:- ')
l1.config(bg="GOLD")
l1.pack()
R1 = Radiobutton(root, text="Option 1 = 1936", variable=var, 				value=1, command=Rel)
R1.config(bg="CYAN")
R1.pack( anchor = W )
R2 = Radiobutton(root, text="Option 2 = 1938", variable=var, 				value=2,command=Rel)
R2.config(bg="CYAN")
R2.pack( anchor = W )
R3 = Radiobutton(root, text="Option 3 = 1939", variable=var, 				value=3,command=Rel)
R3.config(bg="CYAN")
R3.pack( anchor = W)
R4 = Radiobutton(root, text="Option 4 = 1940", variable=var, 				value=4,command=Rel)
R4.config(bg="CYAN")
R4.pack( anchor = W)
label = Label(root)
label.pack()
root.mainloop()

